[tool.poetry]
name = "flatpak_node_generator"
version = "0.1.0"
description = ""
authors = ["Ryan Gonzalez <ryan.gonzalez@collabora.com>", "Filippe LeMarchand <gasinvein@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
blue = {git = "https://github.com/grantjenks/blue"}
isort = "^5.10.1"
poethepoet = "^0.13.1"

[tool.poetry.scripts]
flatpak-node-generator = "flatpak_node_generator.main:main"

[tool.blue]
line-length = 88

[tool.isort]
from_first = true
lines_between_types = 1
profile = "black"

[tool.poe.tasks]
check-format = "blue --check flatpak_node_generator"
check-isort = "isort --check flatpak_node_generator"
check = ["check-format", "check-isort"]

apply-format = "blue flatpak_node_generator"
apply-isort = "isort flatpak_node_generator"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
